// @ts-nocheck
// GENERATED by packages/cli/scripts/bundle-ui.ts — do not edit by hand. Type
// checking is off for this file only: a `with { type: "file" }` import must
// use each asset's real extension for `bun build --compile` to embed it and
// for Bun to infer the right content-type when served, and some of those
// extensions (`.html`) already carry a bun-types ambient module declaration
// that types the default export as something other than `string`.
// `EMBEDDED_ASSETS`'s own annotation below is what every other file sees
// when it imports this one. Regenerated by `bun run build`; empty on a fresh
// checkout that hasn't built the viewer client yet — `resolveClientAssets` in
// `client.ts` falls back to a directory search when this map is empty.

export const EMBEDDED_ASSETS: Record<string, string> = {};
