/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapsMapNameRouteImport } from './routes/maps.$mapName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapNameRoute = MapsMapNameRouteImport.update({
  id: '/maps/$mapName',
  path: '/maps/$mapName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maps/$mapName': typeof MapsMapNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maps/$mapName': typeof MapsMapNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maps/$mapName': typeof MapsMapNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/maps/$mapName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/maps/$mapName'
  id: '__root__' | '/' | '/maps/$mapName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapsMapNameRoute: typeof MapsMapNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$mapName': {
      id: '/maps/$mapName'
      path: '/maps/$mapName'
      fullPath: '/maps/$mapName'
      preLoaderRoute: typeof MapsMapNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapsMapNameRoute: MapsMapNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
