#!/usr/bin/env bun
// Builds the viewer client and copies it into this package, so `wayful ui`
// serves a client the CLI owns rather than one it hopes is in a sibling
// directory. `src/server/client.ts` looks here first, and `bun build
// --compile` embeds the same files straight into the binary via the
// generated `embedded-ui.ts` below.

import { Glob } from "bun";
import { cp, rm } from "node:fs/promises";
import { join, resolve } from "node:path";

const PACKAGE_ROOT = resolve(import.meta.dir, "..");
const UI_ROOT = resolve(PACKAGE_ROOT, "..", "ui");
const SOURCE = join(UI_ROOT, "dist");
const TARGET = join(PACKAGE_ROOT, "dist", "ui");
const EMBEDDED_UI_PATH = join(PACKAGE_ROOT, "src", "server", "embedded-ui.ts");

const build = Bun.spawnSync({
  cmd: ["bun", "run", "build"],
  cwd: UI_ROOT,
  stdout: "inherit",
  stderr: "inherit",
});
if (build.exitCode !== 0) {
  console.error("wayful: viewer client build failed.");
  process.exit(build.exitCode);
}

if (!(await Bun.file(join(SOURCE, "index.html")).exists())) {
  console.error(`wayful: ${SOURCE} has no index.html after building.`);
  process.exit(1);
}

// Replaced rather than merged: a stale hashed asset left behind would be served
// forever, since nothing else ever deletes from this directory.
await rm(TARGET, { force: true, recursive: true });
await cp(SOURCE, TARGET, { recursive: true });

console.log(`wayful: bundled the viewer client into ${TARGET}`);

const embeddedIdentifier = (index: number) => `asset${index}`;
const embeddedSpecifier = (relative: string) => `../../dist/ui/${relative}`;

/**
 * One `import … with { type: "file" }` per built asset, plus a route → import
 * map. `bun build --compile` embeds each imported file into the standalone
 * binary; outside a compile, the same import evaluates to the file's path on
 * disk. Either way `EMBEDDED_ASSETS` is a plain `Record<string, string>` the
 * server can look routes up in directly, with no filesystem resolution left
 * to do at request time.
 */
async function generateEmbeddedUi(): Promise<void> {
  const files: string[] = [];
  for await (const relative of new Glob("**/*").scan({ cwd: TARGET, onlyFiles: true })) {
    files.push(relative);
  }
  files.sort();

  const importLines = files.map(
    (relative, index) =>
      `import ${embeddedIdentifier(index)} from ${JSON.stringify(embeddedSpecifier(relative))} with { type: "file" };`,
  );
  const entries = files.map(
    (relative, index) => `  ${JSON.stringify(`/${relative}`)}: ${embeddedIdentifier(index)},`,
  );
  const indexIndex = files.indexOf("index.html");
  if (indexIndex !== -1) entries.push(`  "/": ${embeddedIdentifier(indexIndex)},`);

  const source = `// @ts-nocheck
// GENERATED by packages/cli/scripts/bundle-ui.ts — do not edit by hand. Type
// checking is off for this file only: a \`with { type: "file" }\` import must
// use each asset's real extension for \`bun build --compile\` to embed it and
// for Bun to infer the right content-type when served, and some of those
// extensions (\`.html\`) already carry a bun-types ambient module declaration
// that types the default export as something other than \`string\`.
// \`EMBEDDED_ASSETS\`'s own annotation below is what every other file sees
// when it imports this one. Regenerated by \`bun run build\`; empty on a fresh
// checkout that hasn't built the viewer client yet — \`resolveClientAssets\` in
// \`client.ts\` falls back to a directory search when this map is empty.
${importLines.length > 0 ? `\n${importLines.join("\n")}\n` : ""}
export const EMBEDDED_ASSETS: Record<string, string> = {
${entries.join("\n")}
};
`;

  await Bun.write(EMBEDDED_UI_PATH, source);
}

await generateEmbeddedUi();
console.log(`wayful: embedded the viewer client into ${EMBEDDED_UI_PATH}`);
